name: Commit and Push 

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  commit_and_push:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: maintenance
        run: |
           echo "maintenance done"
           ls -la 
           python save_to_csv.py
          

